variables:
  DOCKER_TLS_CERTDIR: ""
  APPLICATION_NAME: "fhir-server"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - test
  - build
  - deploy

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.latest.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .m2/repository

sast:
  stage: test
  services:
    - docker:dind
  tags:
    - docker

build:
  stage: build
  image: maven:3.8.1-jdk-11
  script:
    - mvn install -DskipTests
  artifacts:
    paths:
      - target/*.jar

unit-test:
  stage: test
  image: docker.io/library/maven:3.9.4-eclipse-temurin-17
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/*.xml
    paths:
      - target/surefire-reports/
    expire_in: 1 week
  script:
    - mvn test
  only:
    - merge_requests
