services:
  clinomic-fhir-server:
    build:
      context: .
      target: tomcat
    environment:
      APPLICATION_NAME: fhir-server
      SERVER_ADDRESS: 0.0.0.0
      REQUEST_VALIDATION: false
      RESPONSE_VALIDATION: false
      SQL_DIALECT: ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
      SQL_DRIVER: org.h2.Driver
      SQL_URL: jdbc:h2:mem:test_mem
      SQL_USERNAME: sa
      SQL_PASSWORD: null
      OPENSEARCH_ENABLED: false
      OPENSEARCH_URL: localhost:9200
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: admin
      SUBSCRIPTION_REST_ENABLED: false
      SUBSCRIPTION_EMAIL_ENABLED: false
      SUBSCRIPTION_WEBSOCKET_ENABLED: false
      AUDIT_EVENT: false
    ports:
      - "8080:8080"
    volumes:
      - /tmp:/tmp
      - ./lucenefiles:/app/target/lucenefiles/
    depends_on:
      - clinomic-fhir-postgres

  clinomic-fhir-postgres:
    build: ./config/database
    environment:
      SERVER_NAME: fhir
      POSTGRES_DB: hapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata

  karate:
    entrypoint: '/wait-for-it.sh clinomic-fhir-server:8080/fhir -t 60 -- java -cp "/utils/*" com.intuit.karate.Main'
    image: www.clinomic.biz:5050/gsheldija/karate-samples:0.0.1
    environment:
      URL_BASE: 'http://clinomic-fhir-server:8080/fhir'
    volumes:
      - ./tests:/tests
    user: "${UID}:${GID}"
    command:
      - "/tests/integration/custom-configuration.feature"
      - "/tests/integration/auditevent.feature"
      - "/tests/utils.feature"
    depends_on:
      - clinomic-fhir-postgres
      - clinomic-fhir-server


volumes:
  postgres:
    driver: local