services:
  clinomic-fhir-server:
    build:
      context: .
      target: tomcat
    env_file:
      - .env
    ports:
      - 8080:8080
      - 9100:9100
    volumes:
      - /tmp:/tmp
      - ./lucenefiles:/app/target/lucenefiles/
      - ./src/main/resources/logback.xml:/logbackconfig/logback.xml    # See also catalina.properties/logging.config. Now, when running on local docker, changes to logback.xml will be reloaded automatically.
    depends_on:
      - clinomic-fhir-postgres

  clinomic-fhir-postgres:
    build: ./config/database
    environment:
      SERVER_NAME: fhir
      POSTGRES_DB: hapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata

  karate:
    entrypoint: '/wait-for-it.sh clinomic-fhir-server:8080/fhir -t 60 -- java -cp "/utils/*" com.intuit.karate.Main'
    image: www.clinomic.biz:5050/mona/karate:0.0.1
    environment:
      URL_BASE: 'http://clinomic-fhir-server:8080/fhir'
    volumes:
      - ./tests:/tests
    user: "${UID}:${GID}"
    command:
      - "/tests/integration/custom-configuration.feature"
      - "/tests/integration/auditevent.feature"
      - "/tests/integration/scripting.feature"
      - "/tests/integration/terminology.feature"
      - "/tests/utils.feature"
    depends_on:
      - clinomic-fhir-postgres
      - clinomic-fhir-server

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./config/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./config/grafana/fhir-server-dashboard.json:/etc/grafana/provisioning/dashboards/fhir-server-dashboard.json
    environment:
      GF_SECURITY_ADMIN_USER: ${ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: 'false'
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
      - --storage.tsdb.retention.time=30d
    restart: unless-stopped
    depends_on:
      - clinomic-fhir-server
    ports:
      - 9090:9090

volumes:
  postgres:
    driver: local
